<?php

return [
    // The full Layup built-in widget library. The app's own customised widgets
    // (Hero, Rich Text, Image, Feature Grid, Call to Action) are registered after
    // these in AdminPanelProvider, so they override the same widget types.
    'widgets' => [
        // Content
        \Crumbls\Layup\View\TextWidget::class,
        \Crumbls\Layup\View\HeadingWidget::class,
        \Crumbls\Layup\View\BlurbWidget::class,
        \Crumbls\Layup\View\IconWidget::class,
        \Crumbls\Layup\View\AccordionWidget::class,
        \Crumbls\Layup\View\ToggleWidget::class,
        \Crumbls\Layup\View\TabsWidget::class,
        \Crumbls\Layup\View\PersonWidget::class,
        \Crumbls\Layup\View\TestimonialWidget::class,
        \Crumbls\Layup\View\NumberCounterWidget::class,
        \Crumbls\Layup\View\BarCounterWidget::class,

        // Media
        \Crumbls\Layup\View\GalleryWidget::class,
        \Crumbls\Layup\View\VideoWidget::class,
        \Crumbls\Layup\View\AudioWidget::class,
        \Crumbls\Layup\View\SliderWidget::class,
        \Crumbls\Layup\View\MapWidget::class,

        // Interactive
        \Crumbls\Layup\View\ButtonWidget::class,
        \Crumbls\Layup\View\CountdownWidget::class,
        \Crumbls\Layup\View\PricingTableWidget::class,
        \Crumbls\Layup\View\SocialFollowWidget::class,

        // Layout
        \Crumbls\Layup\View\SpacerWidget::class,
        \Crumbls\Layup\View\DividerWidget::class,

        // Advanced
        \Crumbls\Layup\View\HtmlWidget::class,
        \Crumbls\Layup\View\CodeWidget::class,
        \Crumbls\Layup\View\EmbedWidget::class,
        \Crumbls\Layup\View\AlertWidget::class,
        \Crumbls\Layup\View\TableWidget::class,
        \Crumbls\Layup\View\ProgressCircleWidget::class,
        \Crumbls\Layup\View\MenuWidget::class,
        \Crumbls\Layup\View\SearchWidget::class,
        \Crumbls\Layup\View\ContactFormWidget::class,
        \Crumbls\Layup\View\StarRatingWidget::class,
        \Crumbls\Layup\View\LogoGridWidget::class,
        \Crumbls\Layup\View\BlockquoteWidget::class,
        \Crumbls\Layup\View\FeatureListWidget::class,
        \Crumbls\Layup\View\TimelineWidget::class,
        \Crumbls\Layup\View\StatCardWidget::class,
        \Crumbls\Layup\View\MarqueeWidget::class,
        \Crumbls\Layup\View\BeforeAfterWidget::class,
        \Crumbls\Layup\View\TeamGridWidget::class,
        \Crumbls\Layup\View\NotificationBarWidget::class,
        \Crumbls\Layup\View\BreadcrumbsWidget::class,
        \Crumbls\Layup\View\FaqWidget::class,
        \Crumbls\Layup\View\LoginWidget::class,
        \Crumbls\Layup\View\NewsletterWidget::class,
        \Crumbls\Layup\View\PostListWidget::class,
        \Crumbls\Layup\View\SeparatorWidget::class,
        \Crumbls\Layup\View\BackToTopWidget::class,
        \Crumbls\Layup\View\CookieConsentWidget::class,
        \Crumbls\Layup\View\ShareButtonsWidget::class,
        \Crumbls\Layup\View\ModalWidget::class,
        \Crumbls\Layup\View\TypewriterWidget::class,
        \Crumbls\Layup\View\CardWidget::class,
        \Crumbls\Layup\View\TableOfContentsWidget::class,
        \Crumbls\Layup\View\StepProcessWidget::class,
        \Crumbls\Layup\View\GradientTextWidget::class,
        \Crumbls\Layup\View\FlipCardWidget::class,
        \Crumbls\Layup\View\PricingToggleWidget::class,
        \Crumbls\Layup\View\ImageHotspotWidget::class,
        \Crumbls\Layup\View\LottieWidget::class,
        \Crumbls\Layup\View\MasonryWidget::class,
        \Crumbls\Layup\View\ListWidget::class,
        \Crumbls\Layup\View\AnchorWidget::class,
        \Crumbls\Layup\View\BannerWidget::class,
        \Crumbls\Layup\View\ContentToggleWidget::class,
        \Crumbls\Layup\View\LogoSliderWidget::class,
        \Crumbls\Layup\View\TestimonialSliderWidget::class,
        \Crumbls\Layup\View\IconBoxWidget::class,
        \Crumbls\Layup\View\AnimatedHeadingWidget::class,
        \Crumbls\Layup\View\TestimonialCarouselWidget::class,
        \Crumbls\Layup\View\ComparisonTableWidget::class,
        \Crumbls\Layup\View\VideoPlaylistWidget::class,
        \Crumbls\Layup\View\BadgeWidget::class,
        \Crumbls\Layup\View\AvatarGroupWidget::class,
        \Crumbls\Layup\View\TestimonialGridWidget::class,
        \Crumbls\Layup\View\FileDownloadWidget::class,
        \Crumbls\Layup\View\ChangelogWidget::class,
        \Crumbls\Layup\View\SkillBarWidget::class,
        \Crumbls\Layup\View\PriceWidget::class,
        \Crumbls\Layup\View\HotspotWidget::class,
        \Crumbls\Layup\View\MetricWidget::class,
        \Crumbls\Layup\View\HighlightBoxWidget::class,
        \Crumbls\Layup\View\SocialProofWidget::class,
        \Crumbls\Layup\View\CtaBannerWidget::class,
        \Crumbls\Layup\View\IconListWidget::class,
        \Crumbls\Layup\View\ImageCardWidget::class,
        \Crumbls\Layup\View\ImageTextWidget::class,
        \Crumbls\Layup\View\QuoteCarouselWidget::class,
        \Crumbls\Layup\View\SectionHeadingWidget::class,
        \Crumbls\Layup\View\TextColumnsWidget::class,
    ],

    'pages' => [
        'table' => 'layup_pages',
        'model' => \App\Models\Page::class,
        'default_slug' => null,
    ],

    'frontend' => [
        'enabled' => false,
        'prefix' => 'pages',
        'middleware' => ['web'],
        'domain' => null,
        'layout' => 'app',
        'view' => 'layup::frontend.page',
        'max_width' => 'container',
        'include_scripts' => true,
        'excluded_paths' => [],
    ],
];
